---
deployment:
  tasks:
    - export DEPLOYPATH=/home/usuario/public_html  # Ruta de despliegue en cPanel, reemplaza "usuario" con tu nombre de usuario en cPanel

    - git pull origin main  # Obtener los últimos cambios del repositorio, asumiendo que estás en la rama 'main'
      
    - rsync -avz --delete ./ $DEPLOYPATH  # Desplegar los archivos al directorio de despliegue en cPanel
